# Generated by Django 5.2.7 on 2025-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('loading', 'Loading Order'), ('shipped', 'Shipped Order'), ('delivered', 'Delivered Order'), ('processing', 'Procsessing Order'), ('halted', 'Halted Order')], default='processing'),
        ),
    ]
