# Generated by Django 5.2.7 on 2025-11-20 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('0993535f-b7cd-4318-945a-54f7f6a1ed6f'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(db_index=True, max_length=11, unique=True, verbose_name='Phone number')),
                ('first_name', models.CharField(blank=True, max_length=32, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, help_text='their account is active or not', verbose_name='Active')),
                ('is_admin', models.BooleanField(default=False, help_text='whether the use can log into admin site or not', verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
