# Generated by Django 5.2.7 on 2025-11-20 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('92434e5c-1c54-46fa-b527-e6a883c9f7a4'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
